### ISSUE TITLE
stopped working in HA 0.85.0

### ISSUE THREAD

**Issue by rds76** [rogro82/hass-variables#15]
trying to set variable in script
```yaml
    - service: variable.set_variable
      data:
        variable: varxxx
        attributes_template: >
            {
              "history_1": "{{ variable.state }}",
              "history_2": "{{ variable.attributes.history_1 }}",
              "history_3": "{{ variable.attributes.history_2 }}"
            }
      data_template:
        value: "{{ as_timestamp(now())|timestamp_custom('[%d/%m %H:%M] ') ~ message }}"
```
got error:
```
Traceback (most recent call last):
  File ".../homeassistant/.homeassistant/custom_components/variable.py", line 179, in async_set_variable
    attributes = json.loads(attributes_template.async_render({ 'variable': current_state }))
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 59 (char 60)
```

worked before upgrde of HA

**Comment by OleksandrBerchenko** [comment]
I'm not sure that syntax ever worked.  See https://github.com/rogro82/hass-variables/issues/14 .

**Comment by rds76** [comment]
Worked for sure. Used that prior v 0.85.0. At least in attribute_template. Your case is for value_template.

**Comment by rds76** [comment]
FInally there was issue with state content. It contains \n symbol which json did not like. Be carefull as variable need to be escaped before placing them directly to attribute_template json format.
```yaml
data_template:
        value: "{{ as_timestamp(now())|timestamp_custom('[%d/%m %H:%M] ') ~ message|replace('\n',' ') }}"
```
