### ISSUE TITLE
Hass 63.1 Break

### ISSUE THREAD

**Issue by Odianosen25** [rogro82/hass-variables#3]
Hello @rogro82,

Please I have been using your component and its been great until the recent 63.1 update. When I try to update a variable, I get the error 

```
Log Details (ERROR)
Thu Feb 15 2018 09:39:20 GMT+0000 (GMT Standard Time)

Error executing service <ServiceCall variable.set_variable: variable=temp_switch_state, value=1>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1010, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/home/homeassistant/.homeassistant/custom_components/variable.py", line 88, in async_set_variable_service
    entity = component.entities[entity_id]
TypeError: 'itertools.chain' object is not subscriptable
```

Please can you help with this, as a couple of my automation depends on it.

Kind regards

**Comment by rogro82** [comment]
This should be fixed in the last commit. You should update your variable.py file
